// Generated by CoffeeScript 1.7.1
var App;

App = (function() {
  function App(id) {
    this.id = id;
    this.dir = null;
    this.stylFile = null;
    this.clientFile = null;
    this.routes = [];
    this.lang = 'en';
    this.root = '/';
    this["static"] = '/s/';
  }

  return App;

})();

module.exports = App;
