// Generated by CoffeeScript 1.7.1
var Build, build, fs, main, path, runScript, writeAppJs, writeClient, writeCss;

require('coffee-script').register();

path = require('path');

Build = require('web-build-tools').Build;

fs = require('fs');

main = function() {
  var app, e;
  try {
    app = require(path.resolve('./app'));
  } catch (_error) {
    e = _error;
    console.error("Found no `app` in current dir (" + (path.resolve('.')) + ").");
    process.exit(1);
  }
  return build(app);
};

build = function(app) {
  return runScript(app, function() {
    writeAppJs();
    writeCss(app);
    return writeClient(app);
  });
};

runScript = function(app, cb) {
  return Build.sh("rm -fr build\nmkdir build\ncoffee --compile --bare --output build/app app\ncp -r " + __dirname + "/../views build\ncp -r views/* build/views\nmkdir -p build/s/css build/s/js\n\nif [ -d static ]; then\n  cp -r static/* build/s\nfi", cb);
};

writeAppJs = function() {
  return fs.writeFileSync('build/app.js', "var app = require('./app/index');\nvar Site = require('intercessor').Site;\n\nvar site = new Site(app);\nsite.start(function () {});\n");
};

writeCss = function(app, cb) {
  var inFile;
  inFile = __dirname + '/../styles/index.styl';
  return Build.stylus('build/s/css/site.css', inFile, {}, function() {
    if (!app.stylFile) {
      return typeof cb === "function" ? cb() : void 0;
    }
    return Build.stylus('build/s/css/app.css', app.stylFile, {}, cb);
  });
};

writeClient = function(app, cb) {
  var inFile;
  if (!app.clientFile) {
    return typeof cb === "function" ? cb() : void 0;
  }
  inFile = path.resolve(app.clientFile);
  return Build.browserify('build/s/js/client.js', inFile, {}, cb);
};

module.exports = main;
